# Generated by Django 4.1.4 on 2023-05-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.CharField(max_length=500000),
        ),
    ]
